### ISSUE TITLE
Fix credible interval bound calculation

### ISSUE THREAD

**Issue by mermelstein** [bakermoran/BayesABTest#31]
I believe [here](https://github.com/bakermoran/BayesABTest/blob/b0912caba2696888c4670115b02dee7b4214bf9f/BayesABTest/_ab_test_model_plotting.py#L102) and [here](https://github.com/bakermoran/BayesABTest/blob/b0912caba2696888c4670115b02dee7b4214bf9f/BayesABTest/_ab_test_model_plotting.py#L106) the bounds of the credible/confidence interval needs to be cut in half. Eg right now the lower bound is calculated as the percentile of the lift values where `1-confidence_level` such that if confidence_level = 0.1 (90% CI) then the lower bound is the 10th percentile, when it should actually be 5%. By calculating the upper bound in the same manner that it equals the 90th percentile, you end up with a CI that is actually 80%, not 90% as intended.

This could be solved by doing something like:

```python
        lower_bound = x[y.index(min(y,
                                    key=lambda x:
                                    abs(x-self.confidence_level/2)))]
```

**Comment by bakermoran** [comment]
#32 🥳
